import inspect
import os

from libloader import LibInterface


# TODO: Make this platform independent
_libpath = '../../bin/lib/libsnackpack.dylib'

# Find the header directory.
this_file = inspect.getfile(inspect.currentframe())
this_dir = os.path.dirname(os.path.abspath(this_file))
header_dir = os.path.join(this_dir, 'headers')

# These are a list of headers that have been pushed through the preprocessor
# with _PYCPARSER_SCAN_ defined. They should be autogenerated by CMake.
header_list = [
    'blas1_real.h'
]

#header_files = [os.path.join(header_dir, h) for h in header_list]

#blas = LibInterface(_libpath, header_file, 'sp_blas_', strip_prefix=True)
